version: "3.7"

services:
  ubuntu-base:
    build:
      context: .
      args:
        image_cookbook_dir: ./cookbook
        image_build_dir: ./build/ubuntu-base
      dockerfile: build/ubuntu-base/Dockerfile
    image: "ubuntu-base:latest"
    stdin_open: true
    tty: true

  wallabag:
    build:
      context: .
      args:
        image_cookbook_dir: ./cookbook
        image_build_dir: ./build/wallabag
        PHP_VERSION: 8.2
        PHP_COMPOSER_VERSION: 2.2.0
      dockerfile: build/wallabag/Dockerfile
    image: "wallabag:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=wallabag
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallabag
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
      - SYMFONY__ENV__FROM_EMAIL=wallabag@wallabag.com
      - SYMFONY__ENV__DOMAIN_NAME=http://localhost
      - SYMFONY__ENV__SERVER_NAME="Wallabag"
    stdin_open: true
    tty: true
    ports:
      - 80:80
    depends_on:
      - db
      - rabbitmq
    volumes:
      - wallabag_data:/srv/http/wallabag

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: wallabag
      MYSQL_DATABASE: wallabag
      MYSQL_USER: wallabag
      MYSQL_PASSWORD: wallabag
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  memcached:
    image: memcached:latest

volumes:
  wallabag_data:
  db_data:
  rabbitmq_data: