version: "3.7"

services:
  ubuntu-base:
    build:
      context: .
      args:
        image_cookbook_dir: ./cookbook
        image_build_dir: ./build/ubuntu-base
      dockerfile: build/ubuntu-base/Dockerfile
    image: "ubuntu-base:latest"
    stdin_open: true
    tty: true

  wallabag:
    build:
      context: .
      args:
        image_cookbook_dir: ./cookbook
        image_build_dir: ./build/wallabag
        PHP_VERSION: 8.2
        PHP_COMPOSER_VERSION: 2.1.9
      dockerfile: build/wallabag/Dockerfile
    image: "wallabag:latest"
    stdin_open: true
    tty: true
    ports:
      - 80:80
    depends_on:
      - db
      - rabbitmq
    volumes:
      - wallabag_data:/var/www/wallabag/data

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallabag
      MYSQL_USER: wallabag
      MYSQL_PASSWORD: wallabag
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  volumes:
    wallabag_data:
    db_data:
    rabbitmq_data: