#!/usr/bin/env bash

set -e

# Maximum number of open files (for ulimit -n)
NFILES=131072

# Maximum locked memory size (for ulimit -l)
# Used for locking the shared memory log in memory.  If you increase log size,
# you need to increase this number as well
#MEMLOCK=82000

# Open files (usually 1024, which is way too small for varnish)
ulimit -n ${NFILES:-131072}

# Maxiumum locked memory size for shared memory log
#ulimit -l ${MEMLOCK:-82000}

if [ ! -v NC_VARNISH_CONFIG ]; then
    NC_VARNISH_CONFIG="default"
fi

exec /usr/sbin/varnishd \
    -a 0.0.0.0:80 \
    -T 0.0.0.0:6082 \
    -f /etc/varnish/$NC_VARNISH_CONFIG.vcl \
    -s malloc,128M \
    -p feature=+esi_disable_xml_check \
    -p thread_pools=1 \
    -p thread_pool_min=10 \
    -p thread_pool_max=100 \
    -F
