#!/bin/bash

set -e

NFILES=131072
ulimit -n ${NFILES:-131072}

if [ ! -v VARNISH_CONFIG ]; then
    VARNISH_CONFIG="default"
fi

exec /usr/sbin/varnishd \
    -a 0.0.0.0:80 \
    -T 0.0.0.0:6082 \
    -f /etc/varnish/$VARNISH_CONFIG.vcl \
    -s malloc,128M \
    -p feature=+esi_disable_xml_check \
    -p thread_pools=1 \
    -p thread_pool_min=10 \
    -p thread_pool_max=100 \
    -F
