#!/bin/bash

set -e

source_dir="$(dirname "$0")"
source ${source_dir}/../../source/font.sh

SERVICE="${1}"

s6-svc -d "/service/${SERVICE}"
if s6-svstat "/service/${SERVICE}" | grep -q '^down'; then
  echo-success "Service ${SERVICE} - stopped"
else
  echo-error "Service ${SERVICE} is not stopped!"
  echo-info "Service ${SERVICE} is up, PID>" `ps auxf | grep ${SERVICE} | awk '{print $2}' | head -n1`
fi
